spring:
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  datasource:
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL}
auction:
  app:
    jwtExpirationMs: '3600000'
    jwtRefreshExpirationMs: '86400000'
    jwtSecret: AuctionAppSecretKey
    stripe:
      stripeApiKey: ${STRIPE_API_KEY}
      cancelUrl: ${PAYMENT_CANCEL_URL}
      successUrl: ${PAYMENT_SUCCESS_URL}
server:
  error:
    include-message: always
