apiVersion: v1
kind: Secret
metadata:
  name: docker-login
  namespace: {{ .Values.metadata.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.image.auth }}

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
  namespace: {{ .Values.metadata.namespace }}
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.global.username | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.global.password | b64enc }}
