apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: app
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: dGxjcGpzZ3hqdnpoamI=
  SPRING_DATASOURCE_PASSWORD: Yjk5N2FhOTU1YTQ0NjU4YjY1ZTQ2OTEzYmJjOGUxOGJjNWFjNjA5ZjZkZmEwMDllMWVlZDk1NjFkNWRiMDE3Nw== 
