apiVersion: v1
kind: Secret
metadata:
  name: postgres-pass
  namespace: database
type: Opaque
data:
  password: cG9zdGdyZXM=
  SPRING_DATASOURCE_USERNAME: dGxjcGpzZ3hqdnpoamI=
  SPRING_DATASOURCE_PASSWORD: Yjk5N2FhOTU1YTQ0NjU4YjY1ZTQ2OTEzYmJjOGUxOGJjNWFjNjA5ZjZkZmEwMDllMWVlZDk1NjFkNWRiMDE3Nw== 

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-pass
  namespace: app
type: Opaque
data:
  password: cG9zdGdyZXM=
  SPRING_DATASOURCE_USERNAME: dGxjcGpzZ3hqdnpoamI=
  SPRING_DATASOURCE_PASSWORD: Yjk5N2FhOTU1YTQ0NjU4YjY1ZTQ2OTEzYmJjOGUxOGJjNWFjNjA5ZjZkZmEwMDllMWVlZDk1NjFkNWRiMDE3Nw== 
